engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scsslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- db/schema.rb
- features/**/*
- lib/tasks/cucumber.rake
- public/assets/javascripts/ace/**/*
- spec/**/*
