default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hr-til_development

test: &test
  <<: *default
  database: hr-til_test
  user: postgres

cucumber:
  <<: *test

staging:
  <<: *default
  database: hr-til_development

production:
  <<: *default
  database: hr-til_development
