default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hr-til_development

test: &test
  <<: *default
  database: hr-til_test

cucumber:
  <<: *test

production:
  <<: *default
  database: hr-til_development
